#!/usr/bin/env python  # cleanTest.py
import os, subprocess
os.mkdir('life')
os.chdir('life')
os.mkdir('Eukarya')
os.mkdir('Bacteria')
open('methanobacteria~', 'w').close()
open('halobacteria', 'w').close()
open('halobacteria~', 'w').close()
os.chdir('Bacteria')
open('cyanobacteria~', 'w').close()
open('spirochetes~', 'w').close()
os.chdir(os.pardir+os.sep+'Eukarya')
os.mkdir('Animals')
os.chdir('Animals')
open('pigs', 'w').close()
open('pigs~', 'w').close()
open('men', 'w').close()
open('men~', 'w').close()
os.chdir(os.pardir+os.sep+os.pardir+os.sep+os.pardir)
for label in ['Before:', 'After:']:
    print(); print(label)
    print(os.listdir('life'))
    print(os.listdir('life'+os.sep+'Bacteria'))
    print(os.listdir('life'+os.sep+'Eukarya'))
    print(os.listdir('life'+os.sep+'Eukarya'+os.sep+'Animals'))
    subprocess.call('./clean.py')
import shutil
shutil.rmtree('life')
